name: 'Release Please Fork'
description: 'Automates versioning and release creation using a custom fork of release-please'
inputs:
  token:
    description: 'GitHub token'
    required: true
    default: ${{ github.token }}
  config-file:
    description: 'Path to release-please-config.json'
    required: false
    default: 'release-please-config.json'
  manifest-file:
    description: 'Path to .release-please-manifest.json'
    required: false
    default: '.release-please-manifest.json'
outputs:
  releases_created:
    description: 'true if any releases were created'
    value: ${{ steps.run-script.outputs.releases_created }}
  paths_released:
    description: 'JSON string of paths that were released'
    value: ${{ steps.run-script.outputs.paths_released }}
  # Explicitly map desktop outputs as requested
  apps/desktop--release_created:
    description: 'true if desktop release was created'
    value: ${{ steps.run-script.outputs['apps/desktop--release_created'] }}
  apps/desktop--id:
    description: 'Release ID for desktop'
    value: ${{ steps.run-script.outputs['apps/desktop--id'] }}
  apps/desktop--tag_name:
    description: 'Tag name for desktop'
    value: ${{ steps.run-script.outputs['apps/desktop--tag_name'] }}
  apps/desktop--version:
    description: 'Version for desktop'
    value: ${{ steps.run-script.outputs['apps/desktop--version'] }}

runs:
  using: "composite"
  steps:
    - uses: actions/setup-node@v4
      with:
        node-version: 20

    - name: Install release-please fork
      shell: bash
      run: npm install Fanzzzd/release-please#feat/draft-release-force-tag @actions/core

    - name: Run release-please script
      id: run-script
      shell: bash
      env:
        GITHUB_TOKEN: ${{ inputs.token }}
        INPUT_CONFIG_FILE: ${{ inputs.config-file }}
        INPUT_MANIFEST_FILE: ${{ inputs.manifest-file }}
      run: node ${{ github.action_path }}/run.js
